language: python

env:
  - PYTHON=python2.6 BUILDOUT=1.4.3

before_install:
  - sudo apt-get update
  - sudo apt-get install -y -q pound

install:
  - $PYTHON bootstrap.py -v $BUILDOUT
  - ./bin/buildout versions:zc.buildout=$BUILDOUT

script:
  - ./bin/test
  - sudo ./bin/pound start
  - sudo ./bin/cycle
  - sudo ./bin/cycle-nowakeup
  - sudo ./bin/pound stop

