language: python

env:
  - PYTHON=python2.4
  - PYTHON=python2.6

before_install:
  - sudo apt-get update
  - sudo apt-get install -y -q pound

install:
  - $PYTHON bootstrap.py
  - ./bin/buildout

script:
  - ./bin/test
  - sudo ./bin/pound start
  - sudo ./bin/cycle
  - sudo ./bin/cycle-nowakeup
  - sudo ./bin/pound stop

