# vim: set syntax=apache:

#if $listen
Listen ${port}
#end if

#for $i in $interfaces
#if $namevirtualhost
NameVirtualHost ${i.interface}:${i.port}
#end if

<VirtualHost ${i.interface}:${i.port}>
    #if $i.servername
    ServerName ${i.servername}
    #end if
    DocumentRoot ${htdocs}

    CustomLog ${access_log} Combined
    ErrorLog ${error_log}

    RewriteEngine On
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ /index.html

    #if $i.ssl    
    SSLEngine on
    SSLCipherSuite ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP:+eNULL
    SSLCertificateFile ${sslcert}
    SSLCertificateKeyFile ${sslkey}
    #for $a in $sslca
    SSLCACertificateFile ${a}
    #end for
    
    #end if    
    
    Header set Cache-Control "max-age=0, private, must-revalidate, no-cache"

</VirtualHost>

#end for
